blank_issues_enabled: true
contact_links:
  - name: Feature Request
    url: https://ideas.otobo.io
    about: Propose a new feature or an improvement to an existing feature and help shape the future of OTOBO (external).
